### ISSUE TITLE
error running snap.py

### ISSUE THREAD

**Issue by MiChaelinzo** [SpiderLabs/snappy#1]
```
michael@Raze:~/ㄒㄖㄖㄥ丂/snappy$ sudo python3 snap.py
[sudo] password for michael: 
Traceback (most recent call last):
  File "/home/michael/ㄒㄖㄖㄥ丂/snappy/snap.py", line 64, in <module>
    file=sys.argv[1]
         ~~~~~~~~^^^
IndexError: list index out of range
michael@Raze:~/ㄒㄖㄖㄥ丂/snappy$  python3 snap.py
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/home/michael/ㄒㄖㄖㄥ丂/snappy/snap.py", line 64, in <module>
    file=sys.argv[1]
         ~~~~~~~~^^^

```

**Comment by Nougat-User** [comment]
Cringe dude

**Comment by MiChaelinzo** [comment]
> Cringe dude

Cringe dude

**Comment by MiChaelinzo** [comment]
Fixed it need to have .cap .pcapng .pcap to analyze first. I read the code and it doesn't have online mode that it would run airodump and independently scan through the network and analyze for malicious threat actors

**Comment by mikhail-do** [comment]
I have the same problem in Termux on my phone.
I don't understand how to fix it.

@MiChaelinzo, can you explain it more?
Thank you

**Comment by MiChaelinzo** [comment]
> I have the same problem in Termux on my phone. I don't understand how to fix it.
> 
> @MiChaelinzo, can you explain it more? Thank you

first you need a  .cap .pcapng .pcap can be got with using Wireshark, WinDump, tcpdump, Packet Square - Capedit, and Ethereal or wifite/fern-wifi cracker handshakes etc.
